# backend/report_generator.py
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import datetime
import matplotlib.pyplot as plt
import io

router = APIRouter(tags=["Reports"])

# --- Pydantic model for POST data ---
class ReportData(BaseModel):
    lat: float
    lon: float
    max_temp: float
    min_temp: float
    depths: list[float] = []
    temps: list[float] = []
    sals: list[float] = []
    press: list[float] = []

# --- Accept both /generate_report and /generate_report/ ---
@router.post("/generate_report", tags=["Reports"])
@router.post("/generate_report/", tags=["Reports"])
def generate_report(data: ReportData):
    """
    Generates a PDF report with stats + graphs.
    """
    # --- Create matplotlib plots in memory ---
    img_buffers = []

    if data.temps and data.depths:
        plt.figure()
        plt.plot(data.temps, data.depths, "r-o")
        plt.gca().invert_yaxis()
        plt.xlabel("Temperature (°C)")
        plt.ylabel("Depth")
        plt.title("Temperature vs Depth")
        buf = io.BytesIO()
        plt.savefig(buf, format="PNG")
        plt.close()
        buf.seek(0)
        img_buffers.append(buf)

    if data.sals and data.depths:
        plt.figure()
        plt.plot(data.sals, data.depths, "g-o")
        plt.gca().invert_yaxis()
        plt.xlabel("Salinity (PSU)")
        plt.ylabel("Depth")
        plt.title("Salinity vs Depth")
        buf = io.BytesIO()
        plt.savefig(buf, format="PNG")
        plt.close()
        buf.seek(0)
        img_buffers.append(buf)

    if data.temps and data.press:
        plt.figure()
        plt.plot(data.temps, data.press, "b-o")
        plt.gca().invert_yaxis()
        plt.xlabel("Temperature (°C)")
        plt.ylabel("Pressure (dbar)")
        plt.title("Temperature vs Pressure")
        buf = io.BytesIO()
        plt.savefig(buf, format="PNG")
        plt.close()
        buf.seek(0)
        img_buffers.append(buf)

    # --- Create PDF in memory ---
    pdf_buffer = io.BytesIO()
    c = canvas.Canvas(pdf_buffer, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "🌊 Ocean Data Report")

    # Basic Info
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 80, f"Latitude: {data.lat}, Longitude: {data.lon}")
    c.drawString(50, height - 100, f"Generated on: {datetime.datetime.now()}")
    c.drawString(50, height - 120, f"Max Temp: {data.max_temp} °C, Min Temp: {data.min_temp} °C")

    # Insert graphs
    y_pos = height - 180
    for img_buf in img_buffers:
        c.drawImage(ImageReader(img_buf), 50, y_pos - 200, width=500, height=200)
        y_pos -= 220
        if y_pos < 100:
            c.showPage()
            y_pos = height - 50

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Agro Data Visualization System")

    c.save()
    pdf_buffer.seek(0)

    return StreamingResponse(
        pdf_buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": "inline; filename=ocean_report.pdf"}
    )
